production:
  admin_login: "admin"
  admin_fullname: "Mconf Admin"
  admin_email: "my-email@my-domain.com"
  admin_password: "admin"
  bbb_server_name: "Default Server"
  bbb_server_url: "http://my-server.domain.com/bigbluebutton/api"
  bbb_server_salt: "1234567890abcdefghijklmnopqrstuvxz"
  bbb_server_version: "0.8"
  site_name: "Mconf"
  site_description: "Mconf Web Portal"
  site_smtp_login: "my-email@my-domain.com"
  site_smtp_password: "my-password"
  site_locale: "en"
  site_domain: "my-mconf-web.domain.com"
  site_signature: "Mconf Web"
  site_feedback_url: "https://my-server.domain.com/feedback-url"
  site_analytics_code: "UA-12345678-9"
